version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: fvidals-atmoz-sftp_homepage_1
      APP_PORT: 80

  homepage:
    image: fvidals/static-web-server-atmoz-sftp:1.0.0@sha256:0fad8629c4ad435f98a1998cd4c0e44ab2d910928950dfac13d50a7fd19a5cef
    restart: on-failure
    user: '1000:1000'

  server:
    image: atmoz/sftp:alpine@sha256:93d2d9c0e8e3d619e01321bd0eabaf746c9700115f92db5038d2d54b277ed22f
    restart: on-failure
    ports:
      - '2222:22'
    volumes:
      - ${UMBREL_ROOT}/data/storage/downloads:/home/umbrel/downloads
    command: umbrel:${APP_PASSWORD}:1000
